# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dd_app', '0002_remove_crew_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='owner',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
