# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 05:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dd_app', '0003_crew_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
