# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dd_app', '0004_auto_20160112_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='date_created',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
