# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 09:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dd_app', '0006_auto_20160112_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 9, 57, 34, 211726, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
