# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 11:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dd_app', '0008_auto_20160112_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Storys',
            },
        ),
        migrations.AlterField(
            model_name='crew',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 11, 2, 6, 552607, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='story',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd_app.Crew'),
        ),
    ]
