# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 04:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dd_app', '0011_auto_20160118_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 19, 4, 29, 35, 276849, tzinfo=utc), verbose_name='date created'),
        ),
    ]
