# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 07:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dd_app', '0012_auto_20160118_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 20, 7, 11, 58, 86264, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='owner',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
