# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 08:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dd_app', '0013_auto_20160120_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='personality',
            field=models.CharField(choices=[('Angry', 'Angry'), ('A Parental Figure', 'A Parental Figure'), ('Drama-queen', 'Drama-queen'), ('Flirt', 'Flirt'), ('No Change', 'No Change'), ('Party Starter', 'Party Starter'), ('Rebel', 'Rebel'), ('Reckless', 'Reckless'), ('Super-friendly', 'Super-friendly')], default='Angry', max_length=20),
        ),
        migrations.AlterField(
            model_name='crew',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 22, 8, 45, 18, 782819, tzinfo=utc), verbose_name='date created'),
        ),
    ]
