# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dd_app', '0014_auto_20160122_0345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterField(
            model_name='crew',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 23, 3, 10, 17, 357724, tzinfo=utc), verbose_name='date created'),
        ),
    ]
