# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dd_app', '0015_auto_20160122_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberSubStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'SubStory',
                'verbose_name_plural': 'SubStories',
            },
        ),
        migrations.RemoveField(
            model_name='story',
            name='content',
        ),
        migrations.AlterField(
            model_name='crew',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 25, 8, 3, 48, 315912, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='personality',
            field=models.CharField(choices=[('Angry', 'Angry'), ('Parental Figure', 'Parental Figure'), ('Drama-queen', 'Drama-queen'), ('Flirt', 'Flirt'), ('No Change', 'No Change'), ('Party Starter', 'Party Starter'), ('Rebel', 'Rebel'), ('Reckless', 'Reckless'), ('Super-friendly', 'Super-friendly')], default='Angry', max_length=20),
        ),
        migrations.AddField(
            model_name='membersubstory',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd_app.CrewMember'),
        ),
        migrations.AddField(
            model_name='membersubstory',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd_app.Story'),
        ),
    ]
