# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dd_app', '0016_auto_20160125_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='crew',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 25, 8, 40, 49, 558538, tzinfo=utc), verbose_name='date created'),
        ),
    ]
