# Generated by Django 4.0.4 on 2022-04-19 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dd_app', '0018_auto_20160126_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('venue', models.CharField(choices=[('Bar', 'Bar'), ('Music Festival', 'Music Festival'), ('Wedding', 'Wedding')], default='Bar', max_length=20)),
                ('template', models.TextField()),
                ('creator', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'StoryTemplate',
                'verbose_name_plural': 'StoryTemplates',
            },
        ),
        migrations.AlterField(
            model_name='crew',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Genderless', 'Genderless')], default='Genderless', max_length=15),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='personality',
            field=models.CharField(choices=[('Angry', 'Angry'), ('Responsible', 'Responsible'), ('Drama-queen', 'Drama-queen'), ('Neutral', 'Neutral'), ('Reckless', 'Reckless'), ('Super-friendly', 'Super-friendly')], default='Angry', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='venue',
            field=models.CharField(choices=[('Bar', 'Bar'), ('Music Festival', 'Music Festival'), ('Wedding', 'Wedding')], default='Bar', max_length=20),
        ),
    ]
